version: '3'

services:
    app:
        build: .
        container_name: CustomerOP
        ports:
          - "5000:5000"
        volumes:
          - import-csv:/code/data/

volumes:
  import-csv:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/girishbhatta/Documents/Code Challenges/CustomerOp/data/